module.exports = [
"Dream big, start small, and take consistent action every single day until your goals become reality.",
"You are stronger than your excuses, and every challenge you face is an opportunity to prove it to yourself.",
"Great things never come from comfort zones, so step into the unknown and embrace growth with courage.",
"Every step forward counts, no matter how small it may seem, because progress compounds over time.",
"Your mindset shapes your reality, so nurture positivity and watch your world transform.",
"Challenges are opportunities in disguise, pushing you to become the person you were meant to be.",
"Keep moving forward; every setback is simply a setup for an even greater comeback in your life.",
"Mistakes are proof that you are trying, so embrace them, learn from them, and grow stronger.",
"You are capable of more than you know, so push your limits and surprise even yourself.",
"Progress is better than perfection, because taking imperfect action leads to real results.",
"The best way to predict the future is to create it yourself with vision, focus, and action.",
"Small daily improvements add up to remarkable achievements when practiced consistently.",
"Don’t wait for opportunity to knock; create it through effort, skill, and determination.",
"Let your dreams be louder than your doubts, and take steps to make them a reality every day.",
"Success is built on consistency, so keep showing up even when it feels difficult or exhausting.",
"Your only limit is the one you place on yourself, so break free and aim higher than ever before.",
"Start where you are, use what you have, and do what you can to move closer to your goals.",
"Life rewards action, not intention, so take bold steps today instead of waiting for tomorrow.",
"Focus on progress rather than perfection, and celebrate the small victories along the way.",
"Don’t quit, because you are closer to your goals than you realize, and the effort will pay off.",
"Turn your dreams into actionable plans, and then take deliberate steps to make them real.",
"Difficult roads often lead to the most beautiful destinations, so embrace the journey with patience.",
"Fear is temporary, but regret lasts forever, so take courageous actions that honor your potential.",
"Push through the pain, because true growth and transformation live on the other side of struggle.",
"You are your only competition, so focus on being better than your past self every day.",
"Stay patient and persistent, because great achievements take time and consistent effort.",
"Passion fuels perseverance, so pursue what excites you with dedication and enthusiasm.",
"Make today count, because tomorrow is never guaranteed, and every moment is precious.",
"Small victories build confidence, and consistent wins eventually lead to major accomplishments.",
"Every failure is a stepping stone toward success, offering lessons that shape your growth.",
"Rise above the noise and doubt, and let your vision guide you to where you truly belong.",
"Don’t let fear dictate your future; take bold actions that reflect your true potential.",
"Hard work beats talent when talent doesn’t work hard, so commit fully to your craft.",
"Every challenge makes you stronger, and each obstacle is an opportunity to grow wiser.",
"Be brave enough to be yourself, even if it means standing alone against the crowd.",
"Opportunities are created by effort, so take initiative and make things happen for yourself.",
"Make your passion your paycheck, and turn what you love into a sustainable, fulfilling life.",
"Your journey is unique; embrace it fully, learn from it, and celebrate every milestone.",
"Keep believing in yourself, even when others doubt you, because your potential is limitless.",
"Nothing worth having comes easy, so embrace the hard work and dedication it requires.",
"Be fearless in the pursuit of your dreams, and let courage guide every step you take.",
"Action conquers fear, so take small steps consistently to build momentum and confidence.",
"Never settle for less than you deserve, and always strive to reach your highest potential.",
"Focus on what you can control, and release what is beyond your power to change.",
"The harder you work, the luckier you become, so keep striving with energy and focus.",
"Make failure your teacher, not your enemy, and learn lessons that prepare you for greatness.",
"Strive for progress, embrace patience, and celebrate every step forward along the way.",
"Your effort today shapes your tomorrow, so invest energy into actions that matter most.",
"Keep your spirit unbreakable, your mind clear, and your heart committed to your purpose.",
"Your dreams deserve action, not excuses, so pursue them relentlessly and courageously.",
"The most powerful weapon you have is your mindset—guard it and feed it with positivity.",
"Stay consistent even on the days you feel tired; persistence builds momentum and mastery.",
"You don’t need to see the whole staircase—just take the first step and trust the climb ahead.",

"Where there is a will, there is always a way—believe in yourself and the path will appear.",
"You are enough just as you are, and your worth isn’t defined by what you achieve.",
"Peace begins the moment you choose to stop fighting what you cannot control.",
"Sometimes doing nothing and resting is the most productive thing you can do for your soul.",
"You don’t need to be perfect to be loved; you only need to be genuine and kind.",
"Flowers don’t compete with the one next to them—they just bloom. So should you.",
"Let go of what you can’t change and focus on the beauty of what you can create.",
"Even the darkest night ends, and the sun always rises—hold on to hope.",
"Self-love isn’t selfish; it’s the foundation of every healthy connection in life.",
"The more you love yourself, the less validation you’ll need from the world.",
"Every season of your life serves a purpose, even the ones that feel heavy.",
"Take time to appreciate how far you’ve come instead of how far you still have to go.",
"Sometimes growth means walking away from what no longer nurtures your peace.",
"Your peace is too valuable to be disturbed by the opinions of others.",
"Be gentle with yourself; healing takes time, and progress is never linear.",
"Every breath you take is a reminder that you’re still here, still trying, still growing.",
"Love yourself through the process, not just when you reach the outcome.",
"The world becomes brighter when you start seeing yourself through eyes of kindness.",
"You don’t need to rush—everything meant for you will come in its perfect time.",
"Let gratitude be your anchor; even small joys can ground your soul in peace.",
"Never underestimate the quiet power of a calm heart and a clear mind.",
"Be proud of yourself for surviving days you thought you couldn’t.",
"You are not behind; you’re on your own timeline, and that’s perfectly okay.",
"Kindness is contagious—spread it freely and watch it return in beautiful ways.",
"Forgive yourself for past mistakes; they were lessons that shaped who you are.",
"Smile more often—it confuses negativity and strengthens your spirit.",
"Let joy find you in ordinary moments; happiness lives in simplicity.",
"Take care of your thoughts when you’re alone—they shape your peace.",
"The universe responds to the energy you give out—so lead with love and faith.",
"Be your own best friend; talk to yourself like someone you deeply care about.",
"Life is not a race—it’s a journey meant to be experienced, not endured.",
"You can start over at any time; nothing is permanent except your will to grow.",
"Beauty begins the moment you decide to be yourself unapologetically.",
"Hope is stronger than fear; keep believing that brighter days are ahead.",
"Your heart is your compass—trust it even when the path isn’t clear.",
"Calmness is a superpower; don’t let chaos steal your inner peace.",
"The most beautiful people are those who choose kindness in a cruel world.",
"Give yourself credit for blooming in places you were never watered.",
"Don’t compare your life to others; the moon and the sun both shine in their own time.",
"Happiness is not found in perfection but in appreciation of the little things."
];
